### PR TITLE
Try running the tests on a real Python

### PR DESCRIPTION
**Pull request by cclauss**
;-)

### CODE REVIEW

**Comment by cclauss** [comment]
Do not merge.

Bummer.  Travis CI is not turned on for pull requests.  The owner of the this repo would need to go to https://travis-ci.org/profile and __flip the repository switch on__ to get these tests to run on pull requests.

**Comment by maxkrivich** [comment]
@cclauss I try to rewrite this project to post on PyPi, if you are interested add me on Skype or something like that to discuss. All my contacts https://maxkrivich.github.io

**Comment by cclauss** [comment]
Repo switch is not turned on in Travis?

**Comment by maxkrivich** [comment]
@cclauss not yet, I planning finish first beta in next few days and after that Travis.

**Comment by cclauss** [comment]
No rush...  I would drop Python versions that are already end of life 

I would recommend that you test on 2.7, 3.4, 3.6 and optionally "nightly".

- Python 3.2 and 3.3 should be removed as they are already [end of life](https://docs.python.org/devguide/index.html#branchstatus) and we do not what to encourage their use.
- If you pass both 3.4 and 3.6 then you will pass 3.5 so the extra run is not needed.
- "3.5-dev", "3.6-dev", "3.7-dev" will just be a distraction for you and will chew up Travis resources (we need to be kind to the folks at Travis because they are giving us valuable assets for free and we do not what that to go away).

**Comment by maxkrivich** [comment]
@cclauss do you have pypi account?

**Comment by cclauss** [comment]
I do not.  You might check out https://github.com/kennethreitz/setup.py for inspiration.

**Comment by maxkrivich** [comment]
@cclauss thanks, but I still have the problem with a description on [pypi](https://pypi.python.org/pypi/PySlowLoris). Maybe you know what is it?

**Comment by maxkrivich** [comment]
@cclauss turn on travis and coveralls, test no work for now

**Comment by cclauss** [comment]
`setup.py` line 48 becomes:

```python
LONG_DESCRIPTION = '\n'.join(line for line in f
                             if not line.startswith('..')) + '\n'
```

**Comment by maxkrivich** [comment]
@cclauss fix line 48, works but still some problems on pypi

**Comment by cclauss** [comment]
Fixed already.

**Comment by cclauss** [comment]
Create a new issue and give details of what the PyPI problems are.

**Comment by cclauss** [comment]
I do not want to be a maintainer but I will help you find and fix issues.

**Comment by maxkrivich** [comment]
https://github.com/maxkrivich/SlowLoris/issues/2 @cclauss

**Pull request closed without merging**
